In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('semi_labeled.csv')

In [4]:
df.head()

0  1  2  3  4  5  6  7  8  9  ...  491  492  493  494  495  496  497  498  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   499  Target  
0    0       2  
1    0       1  
2    0       0  
3    0       0  
4    0       0  

[5 rows x 501 columns]

In [5]:
X = df.drop(df.iloc[:,5:],axis=1)
Y = df.Target
X.head(10)

0  1  2  3  4
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  0  0  0
4  0  0  0  0  0
5  0  0  0  0  0
6  0  0  0  0  0
7  0  0  0  0  0
8  0  0  0  0  0
9  0  0  0  0  0

In [6]:
#adding Bias
X['B']=1
X.head()

0  1  2  3  4  B
0  0  0  0  0  0  1
1  0  0  0  0  0  1
2  0  0  0  0  0  1
3  0  0  0  0  0  1
4  0  0  0  0  0  1

In [7]:
from sklearn.neural_network import MLPRegressor
mlp = MLPRegressor(solver='lbfgs',activation='logistic',learning_rate_init=0.00001, alpha=1e-5, 
                   hidden_layer_sizes=(6,4,2,1,2,4,6),max_iter=1000000,random_state=111)

In [8]:
mlp.fit(X,X)
predictions = mlp.predict(X)

In [9]:
X.iloc[1]

0    0
1    0
2    0
3    0
4    0
B    1
Name: 1, dtype: int64

In [10]:
predictions[1]

array([ 0.42647894,  0.46691128,  0.46874531,  0.39154158, 11.01102213,
        1.00000072])

In [11]:
predictions[1].shape

(6,)

In [12]:
X.iloc[1]

0    0
1    0
2    0
3    0
4    0
B    1
Name: 1, dtype: int64

In [13]:
predictions[1]

array([ 0.42647894,  0.46691128,  0.46874531,  0.39154158, 11.01102213,
        1.00000072])

In [14]:
print(len(mlp.coefs_))
for i in mlp.coefs_:
    print (i.shape)

8
(6, 6)
(6, 4)
(4, 2)
(2, 1)
(1, 2)
(2, 4)
(4, 6)
(6, 6)


In [15]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [16]:
samp = X.values[0]

In [17]:
samp

array([0, 0, 0, 0, 0, 1], dtype=int64)

In [18]:
l1 = 500
l2 = 150
l3 = 25
l4 = 8
l5 = 25
l6 = 150
l7 = 500

In [19]:
samp.shape

(6,)

In [20]:
l1 = sigmoid(np.dot(samp,mlp.coefs_[0])+mlp.intercepts_[0])
l2 = sigmoid(np.dot(l1,mlp.coefs_[1])+mlp.intercepts_[1])
l3 = sigmoid(np.dot(l2,mlp.coefs_[2])+mlp.intercepts_[2])
l4 = sigmoid(np.dot(l3,mlp.coefs_[3])+mlp.intercepts_[3])

In [21]:
l4[0]

0.3203858502516286

In [22]:
l5 = sigmoid(np.dot(l4,mlp.coefs_[4])+mlp.intercepts_[4])
l6 = sigmoid(np.dot(l5,mlp.coefs_[5])+mlp.intercepts_[5])
l7 = np.dot(l6,mlp.coefs_[6])+mlp.intercepts_[6]
l7

array([1.02379056, 0.23282791, 1.22845833, 0.51830248, 0.86840019,
       1.99343242])